config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :charities
  end

  post 'donate', to: 'website#donate', as: 'donate'

  root to: 'website#index'

end

app/models/app.rb
class App
  def all_charities
    Charity.order(:created_at).all
  end

  def build_charity(attributes = {})
    # NOTE currency is for now fixed to THB.
    Charity.new(attributes.merge(total: 0, currency: "THB"))
  end

  def create_charity(attributes)
    charity = build_charity(attributes)
    charity.save
    charity
  end

  def count_charities
    Charity.count
  end

  def find_charity(id)
    Charity.find_by(id: id)
  end

  def create_user(attributes = {})
    user = User.new(attributes)
    user.save
    user
  end
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  validates :name, presence: true

  def credit_amount(amount)
    self.lock!
    new_total = total + amount
    update_attribute :total, new_total
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable
end

app/controllers/admin/charities_controller.rb
class Admin::CharitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @charities = @app.all_charities
  end

  def new
    @charity = @app.build_charity
  end

  def create
    @charity = @app.create_charity(charity_params)

    if @charity.persisted?
      flash.notice = t(".success")
      redirect_to admin_charities_path
    else
      flash.alert = t(".failure")
      render :new
    end
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_app

  private

  def set_app
    @app = App.new
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @token = nil
  end

  def donate
    charity = params[:charity].to_s.downcase == "random" ? Charity.order("RANDOM()").first :
        Charity.find_by(id: params[:charity])
    if params[:omise_token].present?
      amount = params[:amount].blank? || params[:amount].to_f <= 20.00
      unless amount || !charity
        value = (params[:amount].to_f * 100).to_i

        charge = retrieve_token(params[:omise_token]) ? creatCharge(charity,params[:omise_token],value) :
            createFakeCharge(value)

        if charge.paid
          charity.credit_amount(charge.amount)
          flash.notice = t(".success")
          redirect_to root_path
          return
        end
      end
    end

    @token = charity ? nil : retrieve_token(params[:omise_token])
    flash.now.alert = t(".failure")
    render :index
    return

  end

  private

  def retrieve_token(token)
    begin
      Omise::Token.retrieve(token)
    rescue
      nil
    end
  end

  def creatCharge(charity,token,value)
    charge = Omise::Charge.create({
         amount: value,
         currency: "THB",
         card: token,
         description: "Donation to #{charity.name} [#{charity.id}]",
     })

    charge
  end

  def createFakeCharge(value)
    charge = OpenStruct.new({
        amount: value,
        paid: ((value/100) != 999),
    })
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def m(amount, currency)
    Money.new(amount, currency).format
  end
end

app/views/admin/charities/index.html.erb
<%= t(".title") %>

<ul>
  <% @charities.each do |charity| %>
    <li><%= charity.name %> (<%= m charity.total, charity.currency %>)</li>
  <% end %>
</ul>

<%= link_to t("admin.charities.new.link"), new_admin_charity_path %>

app/views/admin/charities/new.html.erb
<%= form_for [:admin, @charity] do |f| %>

  <h1><%= t(".title") %></h1>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamboon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/layouts/website.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamboon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag "https://cdn.omise.co/omise.js" %>

    <%= javascript_tag do %>
      Omise.setPublicKey("<%= Omise.vault_key %>");
    <% end %>

  </body>
</html>

app/views/website/index.html.erb
<%= form_tag donate_path, id: "donate" do %>

  <p>Pick a charity:</p>
  <%= select(:charity, :category_id, @app.all_charities.collect {|p| [ p.name, p.id ] } + [ [ 'Random Charity', 'random' ] ],
             {:include_blank => 'Please select a charity'},{id: "charity", name: "charity"})%>
  <br>
  <br>
  <div>
    <%= label_tag :amount %><br>
    <%= number_field_tag :amount, 500, step: 0.01 %> THB
  </div>

  <% if @token && @token.card.security_code_check %>

    <%= hidden_field_tag :omise_token, @token.id %>

    <div>
      Number<br>
      **** **** **** <%= @token.card.last_digits %>
    </div>

    <div>
      Name (as on card)<br>
      <%= @token.card.name %>
    </div>

    <div>
      Expires<br>
      <%= @token.card.expiration_month %> / <%= @token.card.expiration_year %>
    </div>

    <div>
      Security Code<br>
      ***
    </div>

    <%= link_to t("website.index.use_another_card"), root_path %>

  <% else %>

    <%= hidden_field_tag :omise_token %>

    <div>
      Number<br>
      <%= text_field_tag nil, nil, placeholder: "XXXX XXXX XXXX XXXX", data: { omise: "number" } %>
    </div>

    <div>
      Name (as on card)<br>
      <%= text_field_tag nil, nil, placeholder: "J DOE", data: { omise: "holder_name" } %>
    </div>

    <div>
      Expires<br>
      <%= text_field_tag nil, nil, size: 4, placeholder: "XX", data: { omise: "expiration_month" } %>
      /
      <%= text_field_tag nil, nil, size: 4, placeholder: "XX", data: { omise: "expiration_year" } %>
    </div>

    <div>
      Security Code<br>
      <%= text_field_tag nil, nil, size: 8, placeholder: "XXX", data: { omise: "security_code" } %>
    </div>

  <% end %>

  <div>
    <%= submit_tag t("website.donate.link") %>
    <span class="cc_error"></span>
  </div>

<% end %>